### PR TITLE
Update support/HAFS from NCAR dtc/hwrf-physics 2020/06/19

### PR DESCRIPTION
**Pull request by climbfuji**
This PR adds the HWRF physics to fv3atm. All development was made in the NCAR fork, branch dtc/hwrf-physics. Commit log from this branch:
```
04/06/2020 MONINEDMF https://github.com/NCAR/ufs-weather-model/pull/15 -> https://github.com/NCAR/ufs-weather-model/pull/35
    git cherry-pick e6fe22ffde6425800b7ed2e1cf3748b606806d28
    git cherry-pick a99d5e73f94f5ffb3bd9bbb1a3dc04171026b6d7
    git cherry-pick 5570528f22a9815437e0ef5b413435a8b9fd5881
    git cherry-pick 2bb15be8cc15c69c178b6e443c0ab8c0d75ef318

04/08/2020 RRTMG https://github.com/NCAR/ufs-weather-model/pull/30 -> https://github.com/NCAR/ufs-weather-model/pull/36
    git cherry-pick 5ab446fe423d9a7ba0172ec782e6346c47c98116
    git cherry-pick 1cbc515c6dff00e729523ff6f922e046179d7dcf
    git cherry-pick c6f51f5090411c737a8d79a27bbf08b8d9b00c28
    git cherry-pick 2a43ab170916fbe60c3d918ff16a510928964e51
    git cherry-pick 73f5dcbc93ae297a6a9880988a8f7a7109f99c2e

04/13/2020 SAS https://github.com/ufs-community/ufs-weather-model/pull/94 -> https://github.com/NCAR/ufs-weather-model/pull/39
    (entire PR)

04/16/2020 FA MP updates https://github.com/NCAR/ufs-weather-model/pull/41 (replaced https://github.com/NCAR/ufs-weather-model/pull/25)
    (entire PR)

05/04/2020 FA/HWRF RRTMG/HWRF SAS bugfixes https://github.com/NCAR/ufs-weather-model/pull/45
    (entire PR)

05/20/2020 update from HAFS community https://github.com/NCAR/ufs-weather-model/pull/48
    (entire PR)

06/18/2020 update from HAFS community https://github.com/NCAR/ufs-weather-model/pull/56
    (entire PR)
```

Associated PRs:
https://github.com/hafs-community/ufs-weather-model/pull/5
https://github.com/hafs-community/fv3atm/pull/5
https://github.com/hafs-community/ccpp-physics/pull/2

For regression testing information, see below **NOT YET**.

### CODE REVIEW

**Review by mzhangw — DISMISSED** [review]
looks good to me

**Review by ligiabernardet — DISMISSED** [review]

**Comment by climbfuji** [comment]
Regression testing on hera.intel against official EMC baseline (using `rt.conf`): all tests passed.

[rt_hera_intel.log](https://github.com/hafs-community/ufs-weather-model/files/4806946/rt_hera_intel.log)
[RegressionTests_hera.intel.log](https://github.com/hafs-community/ufs-weather-model/files/4806947/RegressionTests_hera.intel.log)
[Compile_hera.intel.log](https://github.com/hafs-community/ufs-weather-model/files/4806948/Compile_hera.intel.log)

**Comment by climbfuji** [comment]
Regression testing on hera.intel using `rt_hwrf_physics.conf` against previous regression test baseline created with the NCAR dtc/hwrf-physics branch: all tests passed.

[rt_hwrf_physics_hera_intel.log](https://github.com/hafs-community/ufs-weather-model/files/4807021/rt_hwrf_physics_hera_intel.log)

**Comment by climbfuji** [comment]
@BinLiu-NOAA all three PRs listed as associated PRs above are ready to merge from our side. Please let me know next week when you are ready and we can get started with the merge.

Thanks!

**Comment by BinLiu-NOAA** [comment]
Thanks, @climbfuji ! Once @mzhangw pushed her feature/hwrf_physics branch of HAFS into the hafs-community fork, we will start some workflow level regression tests. After that, we can then merge these pull requests.

Thanks!

**Comment by climbfuji** [comment]
@BinLiu-NOAA all regression tests passed on hera with the cleaned up code in these three PRs. Do you want me to commit 
RegressionTests_hera.intel.log and Compile_hera.intel.log as part of this PR ?

- against official EMC baseline using rt.conf

[rt_hera_intel.log](https://github.com/hafs-community/ufs-weather-model/files/4832075/rt_hera_intel.log)
[RegressionTests_hera.intel.log](https://github.com/hafs-community/ufs-weather-model/files/4832077/RegressionTests_hera.intel.log)
[Compile_hera.intel.log](https://github.com/hafs-community/ufs-weather-model/files/4832078/Compile_hera.intel.log)

- on hera.intel using rt_hwrf_physics.conf: first create temporary baseline, then verify against it

[rt_hera_intel_hwrf_physic_create.log](https://github.com/hafs-community/ufs-weather-model/files/4832079/rt_hera_intel_hwrf_physic_create.log)
[rt_hera_intel_hwrf_physic_verify.log](https://github.com/hafs-community/ufs-weather-model/files/4832080/rt_hera_intel_hwrf_physic_verify.log)

**Comment by BinLiu-NOAA** [comment]
@climbfuji Please feel free to commit in these log files as you see fit. Thanks!

**Comment by climbfuji** [comment]
> @climbfuji Please feel free to commit in these log files as you see fit. Thanks!

Done - are we ready to commit?

**Review by BinLiu-NOAA — DISMISSED** [review]
Ready to merge after the fv3atm level PR goes into support/HAFS.

**Comment by climbfuji** [comment]
@BinLiu-NOAA ufs-weather-model is ready, please check again. Thanks!

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good. Ready to merge. Thanks!

**Pull request merged**
