### PR TITLE
Feature/sync develop 20200703

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
Sync the support/HAFS branch with the latest develop branch of ufs-weather-model.

The following three PRs are to sync hafs_forecast.fd (support/HAFS) with its corresponding ufs-weather-model's develop:

- [hafs-community ccpp-physics PR #3](https://github.com/hafs-community/ccpp-physics/pull/3)
- [hafs-community fv3atm PR #6](https://github.com/hafs-community/fv3atm/pull/6)
- [hafs-community ufs-weather-model PR #6](https://github.com/hafs-community/ufs-weather-model/pull/6)
- [HAFS PR #61](https://github.com/NOAA-EMC/HAFS/pull/61)

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
The ufs-weather-model level regression tests were being done here on Hera:
/scratch1/NCEPDEV/stmp2/Bin.Liu/FV3_RT/rt_138801
with the log file:
/scratch1/NCEPDEV/hwrf/save/Bin.Liu/hafs_202007/sorc/hafs_forecast.fd/tests/RegressionTests_hera.intel.log_20200702
Most of the regression tests passed, but with the following failed ones producing different results from the baseline.

FAILED TESTS:
Test fv3_ccpp_regional_control failed
Test fv3_ccpp_gsd failed
Test fv3_ccpp_rap failed
Test fv3_ccpp_hrrr failed
Test fv3_ccpp_thompson failed
Test fv3_ccpp_thompson_no_aero failed
Test fv3_ccpp_gsd_debug failed
Test fv3_ccpp_gsd_diag3d_debug failed
Test fv3_ccpp_thompson_debug failed
Test fv3_ccpp_thompson_no_aero_debug failed

Need to look into what might have caused these differences.

**Comment by climbfuji** [comment]
> The ufs-weather-model level regression tests were being done here on Hera:
> /scratch1/NCEPDEV/stmp2/Bin.Liu/FV3_RT/rt_138801
> with the log file:
> /scratch1/NCEPDEV/hwrf/save/Bin.Liu/hafs_202007/sorc/hafs_forecast.fd/tests/RegressionTests_hera.intel.log_20200702
> Most of the regression tests passed, but with the following failed ones producing different results from the baseline.
> 
> FAILED TESTS:
> Test fv3_ccpp_regional_control failed
> Test fv3_ccpp_gsd failed
> Test fv3_ccpp_rap failed
> Test fv3_ccpp_hrrr failed
> Test fv3_ccpp_thompson failed
> Test fv3_ccpp_thompson_no_aero failed
> Test fv3_ccpp_gsd_debug failed
> Test fv3_ccpp_gsd_diag3d_debug failed
> Test fv3_ccpp_thompson_debug failed
> Test fv3_ccpp_thompson_no_aero_debug failed
> 
> Need to look into what might have caused these differences.

If this is an update from develop after the latest merge (update GSL physics), then the change in baseline is expected, assuming you maintain your own baseline. It should verify against the official EMC baseline with date tag 20200701.

**Comment by BinLiu-NOAA** [comment]
> If this is an update from develop after the latest merge (update GSL physics), then the change in baseline is expected, assuming you maintain your own baseline. It should verify against the official EMC baseline with date tag 20200701.

@climbfuji The support/HAFS branch does not maintain its own baseline. And the ufs-weather-model level regression test did here is against the official EMC baseline with date tag 20200701. I really had no idea why this fv3_ccpp_regional_control failed (only due to the restart file differences in DZ). And not sure this has also affected other failed tests either.

Bin

**Comment by BinLiu-NOAA** [comment]
This branch was further synced with the latest develop as of 07/07/2020.
Regression tests are on going on Hera.

**Comment by BinLiu-NOAA** [comment]
@mzhangw @climbfuji @ChunxiZhang-NOAA,

Unfortunately, even after being synced with the latest develop/master as of yesterday, the ufs-weather-model level regression tests still failed for the following configurations (due to producing different results):
> vi /scratch1/NCEPDEV/hwrf/save/Bin.Liu/hafs_202007/sorc/hafs_forecast.fd/tests/RegressionTests_hera.intel.log
FAILED TESTS:
Test fv3_ccpp_regional_control failed
Test fv3_ccpp_gsd failed
Test fv3_ccpp_rap failed
Test fv3_ccpp_hrrr failed
Test fv3_ccpp_thompson failed
Test fv3_ccpp_thompson_no_aero failed
Test fv3_ccpp_gsd_debug failed
Test fv3_ccpp_gsd_diag3d_debug failed
Test fv3_ccpp_thompson_debug failed
Test fv3_ccpp_thompson_no_aero_debug failed

Here is my regression test work dir:
/scratch1/NCEPDEV/stmp2/Bin.Liu/FV3_RT/rt_168928

Bin

**Comment by climbfuji** [comment]
> @mzhangw @climbfuji @ChunxiZhang-NOAA,
> 
> Unfortunately, even after being synced with the latest develop/master as of yesterday, the ufs-weather-model level regression tests still failed for the following configurations (due to producing different results):
> 
> > vi /scratch1/NCEPDEV/hwrf/save/Bin.Liu/hafs_202007/sorc/hafs_forecast.fd/tests/RegressionTests_hera.intel.log
> > FAILED TESTS:
> > Test fv3_ccpp_regional_control failed
> > Test fv3_ccpp_gsd failed
> > Test fv3_ccpp_rap failed
> > Test fv3_ccpp_hrrr failed
> > Test fv3_ccpp_thompson failed
> > Test fv3_ccpp_thompson_no_aero failed
> > Test fv3_ccpp_gsd_debug failed
> > Test fv3_ccpp_gsd_diag3d_debug failed
> > Test fv3_ccpp_thompson_debug failed
> > Test fv3_ccpp_thompson_no_aero_debug failed
> 
> Here is my regression test work dir:
> /scratch1/NCEPDEV/stmp2/Bin.Liu/FV3_RT/rt_168928
> 
> Bin

I guess the only way to debug this is to check out the ufs-community develop code and this PR, then use the GFS_debug.F90 utilities that CCPP offers and compare the output side by side.

**Comment by BinLiu-NOAA** [comment]
> > @mzhangw @climbfuji @ChunxiZhang-NOAA,
> > Unfortunately, even after being synced with the latest develop/master as of yesterday, the ufs-weather-model level regression tests still failed for the following configurations (due to producing different results):
> > > vi /scratch1/NCEPDEV/hwrf/save/Bin.Liu/hafs_202007/sorc/hafs_forecast.fd/tests/RegressionTests_hera.intel.log
> > > FAILED TESTS:
> > > Test fv3_ccpp_regional_control failed
> > > Test fv3_ccpp_gsd failed
> > > Test fv3_ccpp_rap failed
> > > Test fv3_ccpp_hrrr failed
> > > Test fv3_ccpp_thompson failed
> > > Test fv3_ccpp_thompson_no_aero failed
> > > Test fv3_ccpp_gsd_debug failed
> > > Test fv3_ccpp_gsd_diag3d_debug failed
> > > Test fv3_ccpp_thompson_debug failed
> > > Test fv3_ccpp_thompson_no_aero_debug failed
> > 
> > 
> > Here is my regression test work dir:
> > /scratch1/NCEPDEV/stmp2/Bin.Liu/FV3_RT/rt_168928
> > Bin
> 
> I guess the only way to debug this is to check out the ufs-community develop code and this PR, then use the GFS_debug.F90 utilities that CCPP offers and compare the output side by side.

@climbfuji Yes, I am already testing the above failed tests under ufs-weather-model develop branch.

Meanwhile, I was trying to compare all the source code differences between these three branches and their corresponding develop/master branches. And I got some questions would like to discuss/confirm with you. So, I was wondering if you have a time for a telecon discussion today or tomorrow (@climbfuji @mzhangw @ChunxiZhang-NOAA)?

Thanks!

Bin

**Comment by climbfuji** [comment]
I can do today, but not tomorrow. My calendar is open for you to view and up to date.

**Comment by mzhangw** [comment]
I am open today

**Comment by BinLiu-NOAA** [comment]
Hi @climbfuji @mzhangw @ChunxiZhang-NOAA ,

A good news is that after the fix during today's telecon discussion, the following regression tests now went through (produced identical results to the baseline):
fv3_ccpp_gsd
fv3_ccpp_rap
fv3_ccpp_hrrr
fv3_ccpp_thompson
fv3_ccpp_thompson_no_aero
fv3_ccpp_gsd_debug
fv3_ccpp_gsd_diag3d_debug
fv3_ccpp_thompson_debug
fv3_ccpp_thompson_no_aero_debug

Currently, only this fv3_ccpp_regional_control failed due to the DZ differences in one of the restart files (which is probably a ufs-weather-model side issue).

I am start running the rt_hwrf_physics.conf test with the DEBUG build mode to see if we can find the cause of its failure.

Thanks!

Bin

**Comment by BinLiu-NOAA** [comment]
A follow up for the hwrf physics scheme related regression tests (which are not included in ufs-weather-model standard regression tests).

The following tests failed:
fv3_ccpp_regional_c768_FA_prod
fv3_ccpp_regional_c768_HWRF_PBL_prod
fv3_ccpp_regional_c768_FA_HWRF_RRTMG_prod
fv3_ccpp_HAFS_v0_hwrf_prod

But the following three ran through:
fv3_ccpp_gfs_v15p2_HWRF_LSM_prod
fv3_ccpp_gfs_v15p2_HWRF_SL_prod
fv3_ccpp_gfs_v15p2_HWRF_LSM_SL_prod

The common thing among the failed tests is they all use the F-A microphysics scheme, so it is possible something updated in the FV3_dycore from the ufs-weather-model (fv3atm)'s develop has broken the F-A scheme.

**Comment by mzhangw** [comment]
Thanks for the nice summary.
I am still looking into this issue and will keep you updated.

**Comment by BinLiu-NOAA** [comment]
Synced with [ufs-weather-model](https://github.com/ufs-community/ufs-weather-model) develop on 07/16/2020.

**Pull request merged**
